import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";

import { ThemeProvider } from "next-themes";
import { SkeletonTheme } from "react-loading-skeleton";
import ParticlesComponent from "@/components/UI/Particles";

const roboto = Roboto({
  variable: "--font-roboto",

  subsets: ["latin"],
  weight: ["400", "700", "500", "600", "900", "200", "300"], // or single: '400'
  style: ["normal", "italic"], // optional
  display: "swap", // optional
});

export const metadata: Metadata = {
  title: "Techida",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable}  antialiased`}>
        <ParticlesComponent id="hero-particles" />

        <SkeletonTheme baseColor="#bbc1bb" highlightColor="#bac8be">
          <ThemeProvider
            attribute="data-theme"
            defaultTheme="dark"
            enableSystem={false}
            storageKey="theme"
          >
            {children}
          </ThemeProvider>
        </SkeletonTheme>
      </body>
    </html>
  );
}
